// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgygrzuacnbuilqyqemk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNneWdyenVhY25idWlscXlxZW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAyNTYxMjAsImV4cCI6MjEwNTgzMjEyMH0.LtDp31-4Q38vfzzV3nFVX9mEpTXpWB5RKCx_Gf9qCLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});